### ISSUE TITLE
No result came back.

### ISSUE THREAD

**Issue by Paul-Lo** [Microsoft/Cognitive-Video-Windows#3]
I just use the sample Windows Form github.com/Microsoft/Cognitive-Video-Windows and upload a just 5 seconds 3 mb mp4, it runs eternally and never came back with result.
Did you guys actually load a mp4 with result came back using this WPF sample?

**Comment by chsienki** [comment]
Hi @Paul-Lo. The Video service was experiencing some delays due to high volume yesterday; can you try again now and see if you still have the same issue?

**Comment by Paul-Lo** [comment]
Thanks, @chsienki ! it works now. 
I notice that there's only free level of Video API now. When it goes to Standard or other pay level, will the video api processing speed be faster? 

Much appreciated.
