### ISSUE TITLE
Can't compile the solution

### ISSUE THREAD

**Issue by ahihudi** [Microsoft/Cognitive-Video-Windows#8]
Error description:

Assembly 'SampleUserControlLibrary' was not found. Verify that you are not missing an assembly reference. Also, verify that your project and all referenced assemblies have been built.	VideoAPI-WPF-Samples	C:\StartUp\Cognitive-Video-Windows-master\Cognitive-Video-Windows-master\Sample-WPF\FaceTrackingPage.xaml	8

**Comment by chsienki** [comment]
This repo has a submodule on which it depends. Unfortunately, Visual Studio won't pick these up automatically, so you'll need to do this from a command prompt: git submodule update --init --recursive for example.
