### ISSUE TITLE
Solution incomplete

### ISSUE THREAD

**Issue by fpizarro** [Microsoft/Cognitive-Video-Windows#9]
Hi, the projects SampleUserControlLibrary and VideoSDK (Portable) are not in downloaded folder as part of this solution.

**Comment by cthrash** [comment]
Does https://github.com/Microsoft/Cognitive-Video-Windows/issues/8 solve it?

**Comment by fpizarro** [comment]
Thanks, I resolve my problem, was with git init/update.
